/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinemaadmin;

/**
 *
 * @author amandacarvalho
 */
import cinemalib.*;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;


public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Admin() {
        initComponents();
        closeAllForms();
    }
    
    ArrayList filmes = new ArrayList();
    ArrayList sessoes = new ArrayList();
    ArrayList salas = new ArrayList();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        cadastroFilmesFrame = new javax.swing.JInternalFrame();
        TituloLabel = new javax.swing.JLabel();
        TituloField = new javax.swing.JTextField();
        DuracaoLabel = new javax.swing.JLabel();
        DuracaoField = new javax.swing.JTextField();
        GeneroLabel = new javax.swing.JLabel();
        GeneroField = new javax.swing.JTextField();
        DiretorLabel = new javax.swing.JLabel();
        DiretorField = new javax.swing.JTextField();
        DistribuidoraLabel = new javax.swing.JLabel();
        DistribuidoraField = new javax.swing.JTextField();
        ClassificacaoLabel = new javax.swing.JLabel();
        ClassificacaoField = new javax.swing.JTextField();
        ElencoLabel = new javax.swing.JLabel();
        ElencoField = new javax.swing.JTextField();
        SinopseLabel = new javax.swing.JLabel();
        SinopseField = new javax.swing.JTextField();
        CadastroFilmeButton = new javax.swing.JButton();
        cadastroSalaFrame = new javax.swing.JInternalFrame();
        CapacidadeSalaLabel = new javax.swing.JLabel();
        CapacidadeSalaField = new javax.swing.JTextField();
        NumerodasalaLabel = new javax.swing.JLabel();
        NumerodaSalaField = new javax.swing.JTextField();
        TipodaSalaLabel = new javax.swing.JLabel();
        TipodaSalaComboBox = new javax.swing.JComboBox<>();
        CadastroSalaButton = new javax.swing.JButton();
        cadastroSessaoFrame = new javax.swing.JInternalFrame();
        TipodaSessaoLabel = new javax.swing.JLabel();
        DiaLabel = new javax.swing.JLabel();
        HorarioLabel = new javax.swing.JLabel();
        TipodaSessaoComboBox = new javax.swing.JComboBox<>();
        DiaComboBox = new javax.swing.JComboBox<>();
        HorarioComboBox = new javax.swing.JComboBox<>();
        IdiomaLabel = new javax.swing.JLabel();
        IdiomaComboBox = new javax.swing.JComboBox<>();
        PrecoLabel = new javax.swing.JLabel();
        PrecoField = new javax.swing.JTextField();
        CadastroSessaoButton = new javax.swing.JButton();
        FilmeLabel = new javax.swing.JLabel();
        SalaLabel = new javax.swing.JLabel();
        FilmeComboBox = new javax.swing.JComboBox<>();
        SalaComboBox = new javax.swing.JComboBox<>();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        cadastroMenu = new javax.swing.JMenu();
        cadastroFilmesMenu = new javax.swing.JMenuItem();
        cadastroSalaMenu = new javax.swing.JMenuItem();
        cadastroSessãoMenu = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        desktopPane.setLayout(null);

        cadastroFilmesFrame.setClosable(true);
        cadastroFilmesFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        cadastroFilmesFrame.setTitle("Cadastro Filmes");
        cadastroFilmesFrame.setPreferredSize(new java.awt.Dimension(800, 600));
        cadastroFilmesFrame.setVisible(false);

        TituloLabel.setText("Titulo:");

        DuracaoLabel.setText("Duração:");

        DuracaoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DuracaoFieldActionPerformed(evt);
            }
        });

        GeneroLabel.setText("Gênero:");

        GeneroField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneroFieldActionPerformed(evt);
            }
        });

        DiretorLabel.setText("Diretor:");

        DistribuidoraLabel.setText("Distribuidora:");

        DistribuidoraField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistribuidoraFieldActionPerformed(evt);
            }
        });

        ClassificacaoLabel.setText("Classificação Indicativa:");

        ClassificacaoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassificacaoFieldActionPerformed(evt);
            }
        });

        ElencoLabel.setText("Elenco:");

        ElencoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElencoFieldActionPerformed(evt);
            }
        });

        SinopseLabel.setText("Sinopse:");

        SinopseField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SinopseFieldActionPerformed(evt);
            }
        });

        CadastroFilmeButton.setText("Cadastrar Filme");
        CadastroFilmeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroFilmeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cadastroFilmesFrameLayout = new javax.swing.GroupLayout(cadastroFilmesFrame.getContentPane());
        cadastroFilmesFrame.getContentPane().setLayout(cadastroFilmesFrameLayout);
        cadastroFilmesFrameLayout.setHorizontalGroup(
            cadastroFilmesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroFilmesFrameLayout.createSequentialGroup()
                .addGroup(cadastroFilmesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cadastroFilmesFrameLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CadastroFilmeButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadastroFilmesFrameLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(cadastroFilmesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastroFilmesFrameLayout.createSequentialGroup()
                                .addComponent(ClassificacaoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ClassificacaoField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(cadastroFilmesFrameLayout.createSequentialGroup()
                                .addGroup(cadastroFilmesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadastroFilmesFrameLayout.createSequentialGroup()
                                        .addComponent(DiretorLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DiretorField))
                                    .addGroup(cadastroFilmesFrameLayout.createSequentialGroup()
                                        .addComponent(DuracaoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DuracaoField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(cadastroFilmesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cadastroFilmesFrameLayout.createSequentialGroup()
                                        .addComponent(GeneroLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(GeneroField))
                                    .addGroup(cadastroFilmesFrameLayout.createSequentialGroup()
                                        .addComponent(DistribuidoraLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DistribuidoraField))))
                            .addGroup(cadastroFilmesFrameLayout.createSequentialGroup()
                                .addComponent(ElencoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ElencoField))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadastroFilmesFrameLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(TituloLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TituloField))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadastroFilmesFrameLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(SinopseLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SinopseField)))
                .addGap(82, 82, 82))
        );
        cadastroFilmesFrameLayout.setVerticalGroup(
            cadastroFilmesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroFilmesFrameLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(cadastroFilmesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TituloLabel)
                    .addComponent(TituloField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroFilmesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DuracaoLabel)
                    .addComponent(DuracaoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GeneroLabel)
                    .addComponent(GeneroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroFilmesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DiretorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DistribuidoraField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DistribuidoraLabel)
                    .addComponent(DiretorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroFilmesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClassificacaoLabel)
                    .addComponent(ClassificacaoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroFilmesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ElencoField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ElencoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroFilmesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SinopseField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SinopseLabel))
                .addGap(26, 26, 26)
                .addComponent(CadastroFilmeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        desktopPane.add(cadastroFilmesFrame);
        cadastroFilmesFrame.setBounds(20, 40, 490, 290);

        cadastroSalaFrame.setClosable(true);
        cadastroSalaFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        cadastroSalaFrame.setTitle("Cadastro de Salas");
        cadastroSalaFrame.setVisible(true);
        cadastroSalaFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cadastroSalaFrameMousePressed(evt);
            }
        });

        CapacidadeSalaLabel.setText("Capacidade da Sala:");

        CapacidadeSalaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapacidadeSalaFieldActionPerformed(evt);
            }
        });

        NumerodasalaLabel.setText("Identificador (número) da Sala:");

        NumerodaSalaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumerodaSalaFieldActionPerformed(evt);
            }
        });

        TipodaSalaLabel.setText("Tipo da sala:");

        TipodaSalaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2D", "3D", "XD" }));
        TipodaSalaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipodaSalaComboBoxActionPerformed(evt);
            }
        });

        CadastroSalaButton.setText("Cadastrar Sala");
        CadastroSalaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroSalaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cadastroSalaFrameLayout = new javax.swing.GroupLayout(cadastroSalaFrame.getContentPane());
        cadastroSalaFrame.getContentPane().setLayout(cadastroSalaFrameLayout);
        cadastroSalaFrameLayout.setHorizontalGroup(
            cadastroSalaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroSalaFrameLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(cadastroSalaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastroSalaFrameLayout.createSequentialGroup()
                        .addComponent(CapacidadeSalaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CapacidadeSalaField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cadastroSalaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(cadastroSalaFrameLayout.createSequentialGroup()
                            .addComponent(TipodaSalaLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TipodaSalaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(cadastroSalaFrameLayout.createSequentialGroup()
                            .addComponent(NumerodasalaLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(NumerodaSalaField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(203, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroSalaFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CadastroSalaButton)
                .addContainerGap())
        );
        cadastroSalaFrameLayout.setVerticalGroup(
            cadastroSalaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroSalaFrameLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(cadastroSalaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CapacidadeSalaLabel)
                    .addComponent(CapacidadeSalaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cadastroSalaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumerodasalaLabel)
                    .addComponent(NumerodaSalaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cadastroSalaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipodaSalaLabel)
                    .addComponent(TipodaSalaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CadastroSalaButton)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        desktopPane.add(cadastroSalaFrame);
        cadastroSalaFrame.setBounds(140, 20, 660, 430);

        cadastroSessaoFrame.setClosable(true);
        cadastroSessaoFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        cadastroSessaoFrame.setTitle("Cadastro Sessão");
        cadastroSessaoFrame.setVisible(true);

        TipodaSessaoLabel.setText("Tipo da Sessão:");

        DiaLabel.setText("Dia:");

        HorarioLabel.setText("Horário:");

        TipodaSessaoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Estreia", "Pré-estreia" }));
        TipodaSessaoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipodaSessaoComboBoxActionPerformed(evt);
            }
        });

        DiaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado" }));

        HorarioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matinê", "Noturno" }));

        IdiomaLabel.setText("Idioma:");

        IdiomaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dublado", "Legendado", " " }));

        PrecoLabel.setText("Preço (inteira) :");

        PrecoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecoFieldActionPerformed(evt);
            }
        });

        CadastroSessaoButton.setText("Cadastrar Sessão");
        CadastroSessaoButton.setToolTipText("");
        CadastroSessaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroSessaoButtonActionPerformed(evt);
            }
        });

        FilmeLabel.setText("Filme:");

        SalaLabel.setText("Sala:");

        FilmeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        FilmeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilmeComboBoxActionPerformed(evt);
            }
        });

        SalaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout cadastroSessaoFrameLayout = new javax.swing.GroupLayout(cadastroSessaoFrame.getContentPane());
        cadastroSessaoFrame.getContentPane().setLayout(cadastroSessaoFrameLayout);
        cadastroSessaoFrameLayout.setHorizontalGroup(
            cadastroSessaoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroSessaoFrameLayout.createSequentialGroup()
                .addGroup(cadastroSessaoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cadastroSessaoFrameLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(cadastroSessaoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastroSessaoFrameLayout.createSequentialGroup()
                                .addGroup(cadastroSessaoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cadastroSessaoFrameLayout.createSequentialGroup()
                                        .addComponent(DiaLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DiaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(cadastroSessaoFrameLayout.createSequentialGroup()
                                        .addComponent(TipodaSessaoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TipodaSessaoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(cadastroSessaoFrameLayout.createSequentialGroup()
                                        .addComponent(SalaLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(SalaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(cadastroSessaoFrameLayout.createSequentialGroup()
                                        .addComponent(HorarioLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(HorarioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(cadastroSessaoFrameLayout.createSequentialGroup()
                                        .addComponent(IdiomaLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(IdiomaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(cadastroSessaoFrameLayout.createSequentialGroup()
                                        .addComponent(PrecoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(PrecoField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE))
                            .addGroup(cadastroSessaoFrameLayout.createSequentialGroup()
                                .addComponent(FilmeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FilmeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(cadastroSessaoFrameLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CadastroSessaoButton)))
                .addGap(227, 227, 227))
        );
        cadastroSessaoFrameLayout.setVerticalGroup(
            cadastroSessaoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroSessaoFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadastroSessaoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FilmeLabel)
                    .addComponent(FilmeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroSessaoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalaLabel)
                    .addComponent(SalaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroSessaoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipodaSessaoLabel)
                    .addComponent(TipodaSessaoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroSessaoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DiaLabel)
                    .addComponent(DiaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroSessaoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HorarioLabel)
                    .addComponent(HorarioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroSessaoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdiomaLabel)
                    .addComponent(IdiomaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroSessaoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrecoLabel)
                    .addComponent(PrecoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CadastroSessaoButton)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        desktopPane.add(cadastroSessaoFrame);
        cadastroSessaoFrame.setBounds(40, 50, 678, 357);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        cadastroMenu.setText("Cadastro");

        cadastroFilmesMenu.setText("Filmes");
        cadastroFilmesMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cadastroFilmesMenuMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastroFilmesMenuMouseClicked(evt);
            }
        });
        cadastroFilmesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroFilmesMenuActionPerformed(evt);
            }
        });
        cadastroMenu.add(cadastroFilmesMenu);

        cadastroSalaMenu.setText("Salas");
        cadastroSalaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cadastroSalaMenuMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastroSalaMenuMouseClicked(evt);
            }
        });
        cadastroSalaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroSalaMenuActionPerformed(evt);
            }
        });
        cadastroMenu.add(cadastroSalaMenu);
        cadastroSalaMenu.getAccessibleContext().setAccessibleName("cadastroSalaMenu");

        cadastroSessãoMenu.setText("Sessões");
        cadastroSessãoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cadastroSessãoMenuMousePressed(evt);
            }
        });
        cadastroSessãoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroSessãoMenuActionPerformed(evt);
            }
        });
        cadastroMenu.add(cadastroSessãoMenu);

        menuBar.add(cadastroMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void cadastroFilmesMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroFilmesMenuMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cadastroFilmesMenuMouseClicked

    private void cadastroFilmesMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroFilmesMenuMousePressed
        // TODO add your handling code here:
        closeAllForms();
        cadastroFilmesFrame.setVisible(true);
        cadastroFilmesFrame.setSize(700, 500);
    }//GEN-LAST:event_cadastroFilmesMenuMousePressed

    private void DuracaoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DuracaoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DuracaoFieldActionPerformed

    private void GeneroFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneroFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeneroFieldActionPerformed

    private void ElencoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElencoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ElencoFieldActionPerformed

    private void SinopseFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SinopseFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SinopseFieldActionPerformed

    private void cadastroFilmesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroFilmesMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroFilmesMenuActionPerformed

    private void DistribuidoraFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistribuidoraFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DistribuidoraFieldActionPerformed

    private void cadastroSalaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroSalaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroSalaMenuActionPerformed

    private void CapacidadeSalaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapacidadeSalaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapacidadeSalaFieldActionPerformed

    private void TipodaSalaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipodaSalaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipodaSalaComboBoxActionPerformed
   
    private void cadastroSalaFrameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroSalaFrameMousePressed
        // TODO add your handling code here:
        closeAllForms();
        cadastroSalaFrame.setVisible(true);
        cadastroSalaFrame.setSize(700, 500);
    }//GEN-LAST:event_cadastroSalaFrameMousePressed

    private void cadastroSalaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroSalaMenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroSalaMenuMouseClicked

    private void cadastroSessãoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroSessãoMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroSessãoMenuActionPerformed

    private void cadastroSalaMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroSalaMenuMousePressed
        // TODO add your handling code here:
        closeAllForms();
        cadastroSalaFrame.setVisible(true);
        cadastroSalaFrame.setSize(700, 500);
    }//GEN-LAST:event_cadastroSalaMenuMousePressed

    private void cadastroSessãoMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroSessãoMenuMousePressed
        // TODO add your handling code here:
        closeAllForms();
        cadastroSessaoFrame.setVisible(true);
        cadastroSessaoFrame.setSize(700, 500);
    }//GEN-LAST:event_cadastroSessãoMenuMousePressed

    private void CadastroSalaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroSalaButtonActionPerformed
        // TODO add your handling code here:
        Sala s1 = new Sala();
        s1.setCapacidade(CapacidadeSalaField.getText());
        s1.setTipoSala((String) TipodaSalaComboBox.getSelectedItem());
        s1.setNumero(NumerodaSalaField.getText());
        salas.add(s1);
        this.limpaCamposSalas();
        JOptionPane.showMessageDialog(null,"Sala cadastrada com sucesso!");
    }//GEN-LAST:event_CadastroSalaButtonActionPerformed

    private void CadastroSessaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroSessaoButtonActionPerformed
        // TODO add your handling code here:
        Sessao se1 = new Sessao();

        se1.setSala((String) SalaComboBox.getSelectedItem());
        se1.setFilme((String) FilmeComboBox.getSelectedItem());
        se1.setTipoSessao((String) TipodaSessaoComboBox.getSelectedItem());
        se1.setDia((String) DiaComboBox.getSelectedItem());
        se1.setHorario((String) HorarioComboBox.getSelectedItem());
        se1.setIdioma((String) IdiomaComboBox.getSelectedItem());
        se1.setPreco(PrecoField.getText());
        sessoes.add(se1);
        this.limpaCamposFilmes();
        JOptionPane.showMessageDialog(null,"Sessão cadastrada com sucesso!");
    }//GEN-LAST:event_CadastroSessaoButtonActionPerformed

    private void PrecoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecoFieldActionPerformed

    private void TipodaSessaoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipodaSessaoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipodaSessaoComboBoxActionPerformed

    private void CadastroFilmeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroFilmeButtonActionPerformed
        // TODO add your handling code here:
        Filme f1 = new Filme();
        f1.setNome(TituloField.getText());
        f1.setDuracao(DuracaoField.getText());
        f1.setGenero(GeneroField.getText());
        f1.setDiretor(DiretorField.getText());
        f1.setDistribuidora(DistribuidoraField.getText());
        f1.setClassificacao(ClassificacaoField.getText());
        f1.setElenco(ElencoField.getText());
        f1.setSinopse(SinopseField.getText());
        filmes.add(f1);
        this.limpaCamposFilmes();
        JOptionPane.showMessageDialog(null,"Filme cadastrado com sucesso!");
    }//GEN-LAST:event_CadastroFilmeButtonActionPerformed

    private void ClassificacaoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassificacaoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClassificacaoFieldActionPerformed

    private void NumerodaSalaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumerodaSalaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumerodaSalaFieldActionPerformed

    private void FilmeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilmeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FilmeComboBoxActionPerformed
        
    /**
     * @param args the command line arguments
     */
    //}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastroFilmeButton;
    private javax.swing.JButton CadastroSalaButton;
    private javax.swing.JButton CadastroSessaoButton;
    private javax.swing.JTextField CapacidadeSalaField;
    private javax.swing.JLabel CapacidadeSalaLabel;
    private javax.swing.JTextField ClassificacaoField;
    private javax.swing.JLabel ClassificacaoLabel;
    private javax.swing.JComboBox<String> DiaComboBox;
    private javax.swing.JLabel DiaLabel;
    private javax.swing.JTextField DiretorField;
    private javax.swing.JLabel DiretorLabel;
    private javax.swing.JTextField DistribuidoraField;
    private javax.swing.JLabel DistribuidoraLabel;
    private javax.swing.JTextField DuracaoField;
    private javax.swing.JLabel DuracaoLabel;
    private javax.swing.JTextField ElencoField;
    private javax.swing.JLabel ElencoLabel;
    private javax.swing.JComboBox<String> FilmeComboBox;
    private javax.swing.JLabel FilmeLabel;
    private javax.swing.JTextField GeneroField;
    private javax.swing.JLabel GeneroLabel;
    private javax.swing.JComboBox<String> HorarioComboBox;
    private javax.swing.JLabel HorarioLabel;
    private javax.swing.JComboBox<String> IdiomaComboBox;
    private javax.swing.JLabel IdiomaLabel;
    private javax.swing.JTextField NumerodaSalaField;
    private javax.swing.JLabel NumerodasalaLabel;
    private javax.swing.JTextField PrecoField;
    private javax.swing.JLabel PrecoLabel;
    private javax.swing.JComboBox<String> SalaComboBox;
    private javax.swing.JLabel SalaLabel;
    private javax.swing.JTextField SinopseField;
    private javax.swing.JLabel SinopseLabel;
    private javax.swing.JComboBox<String> TipodaSalaComboBox;
    private javax.swing.JLabel TipodaSalaLabel;
    private javax.swing.JComboBox<String> TipodaSessaoComboBox;
    private javax.swing.JLabel TipodaSessaoLabel;
    private javax.swing.JTextField TituloField;
    private javax.swing.JLabel TituloLabel;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JInternalFrame cadastroFilmesFrame;
    private javax.swing.JMenuItem cadastroFilmesMenu;
    private javax.swing.JMenu cadastroMenu;
    private javax.swing.JInternalFrame cadastroSalaFrame;
    private javax.swing.JMenuItem cadastroSalaMenu;
    private javax.swing.JInternalFrame cadastroSessaoFrame;
    private javax.swing.JMenuItem cadastroSessãoMenu;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

    private void closeAllForms(){
    cadastroFilmesFrame.setVisible(false);
    cadastroSalaFrame.setVisible(false);
    cadastroSessaoFrame.setVisible(false);
    }
    
    ArrayList getFilmes(){
        return filmes;
    }
    ArrayList getSessoes(){
        return sessoes;
    }
    ArrayList getSalas(){
        return salas;
    }
    
    void limpaCamposFilmes(){
        
        TituloField.setText("");
        DuracaoField.setText("");
        GeneroField.setText("");
        DiretorField.setText("");
        TituloField.setText("");
        ClassificacaoField.setText("");
        ElencoField.setText("");
        SinopseField.setText("");
        DistribuidoraField.setText("");
        TituloField.requestFocus();
        
    }
    
    void limpaCamposSessoes(){
        
        PrecoField.setText("");
        PrecoField.requestFocus();
    
    }
    
    void limpaCamposSalas(){
        
        CapacidadeSalaField.setText("");
        NumerodaSalaField.requestFocus();
        CapacidadeSalaField.requestFocus();
        
    }
    
    void setFilmeComboBox(){
        for (Iterator iterator = filmes.iterator(); iterator.hasNext();) {
            Filme next = (Filme) iterator.next();
            FilmeComboBox.addItem(next.getNome());
        }
    }
    void setSalaComboBox(){
        for (Iterator iterator = salas.iterator(); iterator.hasNext();) {
            Sala next = (Sala) iterator.next();
            SalaComboBox.addItem(next.getNumero());
        }
    }
    
}
